# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: E-lang
email: e-lang@univ-lr.fr

description: > # this means to ignore newlines until "baseurl:"
  E-Lang is a project hosted at the University of La Rochelle (France).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://e-lang.github.io" # the base hostname & protocol for your site
twitter_username: chdemko
github_username:  chdemko

# Build settings
markdown: kramdown
